// front-end/src/pages/LoginPage.vue
<template>
  <div class="login-container">
    <h1>Login</h1>
    <form @submit.prevent="submitLogin">
      <div class="form-group">
        <label for="username">Username:</label>
        <input
            type="text"
            id="username"
            v-model="username"
            placeholder="Enter your username"
            required
        />
      </div>

      <div class="form-group">
        <label for="password">Password:</label>
        <input
            type="password"
            id="password"
            v-model="password"
            placeholder="Enter your password"
            required
        />
      </div>

      <button type="submit">Login</button>

      <p v-if="errorMessage" class="error">{{ errorMessage }}</p>
    </form>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  data() {
    return {
      username: '',
      password: '',
      errorMessage: '',
    };
  },
  methods: {
    async submitLogin() {
      try {
        const response = await axios.post('http://127.0.0.1:3000/login', {
          username: this.username,
          password: this.password,
        }, {
          headers: {
            'Content-Type': 'application/json',
          },
        });

        if (response.data.message === 'Login successful') {
          localStorage.setItem('isAuthenticated', true);
          this.$router.push({ name: 'Home' });
        } else {
          this.errorMessage = response.data.message;
        }
      } catch (error) {
        console.error('Login failed:', error);
        this.errorMessage = 'An error occurred. Please try again.';
      }
    },
  },
};
</script>

// front-end/src/LoginPage.jsx
import { useState } from 'react';

function LoginPage() {
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');

    const handleSubmit = async (event) => {
        event.preventDefault();
        const data = {
            username,
            password,
        };

        try {
            const response = await fetch('http://127.0.0.1:3000/login', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(data),
            });

            if (response.ok) {
                const result = await response.json();
                console.log('Success:', result);
            } else {
                console.error('Error:', response.status);
            }
        } catch (error) {
            console.error('Request failed:', error);
        }
};

    return (
        <form onSubmit={handleSubmit}>
            <label>
                Username:
                <input type="text" value={username} onChange={(e) => setUsername(e.target.value)} />
            </label>
            <label>
                Password:
                <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
            </label>
            <button type="submit">Login</button>
        </form>
    );
}

export default LoginPage;
